

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "ArmyViewer.Web\Web.config"
//     Connection String Name: "DefaultConnection"
//     Connection String:      "Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=D:\Source\critmiss\ArmyViewer\ArmyViewer.Data\App_Data\\aspnet-ArmyViewer.Web-20181201014950.mdf;Initial Catalog=aspnet-ArmyViewer.Web-20181201014950;Integrated Security=True"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables().
// -----------------------------------------------------------------------------------------
Cannot attach the file 'D:\Source\critmiss\ArmyViewer\ArmyViewer.Data\App_Data\\aspnet-ArmyViewer.Web-20181201014950.mdf' as database 'aspnet-ArmyViewer.Web-20181201014950'.
System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.VisualStudio.TextTemplatingC9E2107878804C9026754DBDC47AB4F50E60FA2142AAFACA6F2C72D07B019590640FBB14570C627456D7E7EEB733642497CAF9A5D3B84FFB9C2DE1F2DCABD095.GeneratedTextTransformation.LoadTables(DbProviderFactory factory) in D:\Source\critmiss\ArmyViewer\ArmyViewer.Data\EF.Reverse.POCO.Core.ttinclude:line 716




// -----------------------------------------------------------------------------------------
// Failed to read database schema for stored procedures.
// -----------------------------------------------------------------------------------------
Cannot attach the file 'D:\Source\critmiss\ArmyViewer\ArmyViewer.Data\App_Data\\aspnet-ArmyViewer.Web-20181201014950.mdf' as database 'aspnet-ArmyViewer.Web-20181201014950'.
System.Data.SqlClient.SqlException
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.VisualStudio.TextTemplatingC9E2107878804C9026754DBDC47AB4F50E60FA2142AAFACA6F2C72D07B019590640FBB14570C627456D7E7EEB733642497CAF9A5D3B84FFB9C2DE1F2DCABD095.GeneratedTextTransformation.LoadStoredProcs(DbProviderFactory factory) in D:\Source\critmiss\ArmyViewer\ArmyViewer.Data\EF.Reverse.POCO.Core.ttinclude:line 827



